### ISSUE TITLE
WYSIWYG editor fields are showing markup in the browser

### ISSUE THREAD

**Issue by jordelver** [pushtype/push_type#2]
Should those fields have `#html_safe` on them automatically?

```
 <div><%= @node.body.html_safe %></div>
```

<img width="463" alt="2015-08-24 at 22 56" src="https://cloud.githubusercontent.com/assets/6588/9473731/541c9c76-4b54-11e5-9c91-b4d6f7963567.png">

**Comment by aaronrussell** [comment]
https://discuss.pushtype.org/t/wysiwyg-editor-fields-are-showing-markup-in-the-browser/21
