### ISSUE TITLE
ActiveRecord::RecordNotFound in FrontEndController#show

### ISSUE THREAD

**Issue by joeczucha** [pushtype/push_type#25]
Having a bit of an issue with the Getting Started guide.

Steps to reproduce: 

    rails new pushtype --database=postgresql && cd pushtype
Add `gem 'push_type'` >> `.gemfile`

    bundle install
    rake db:create
    rails g push_type:install
    rake push_type:create_user (step through create user process)
    rails s

Visit http://localhost:3000/push_type or http://localhost:3000/push_type/admin in browser

Expected behaviour:

See the PushType dashboard

Actual behaviour: 

> ActiveRecord::RecordNotFound in FrontEndController#show

    push_type_core (0.10.0) app/controllers/front_end_controller.rb:41:in `raise_404'
    push_type_core (0.10.0) app/controllers/front_end_controller.rb:33:in `build_presenter'
    activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
    activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
    actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
    ...

Rails 5.0.0.1
ruby 2.3.2p217
OSX

Thanks for your work on this. Let me know if you need anything further.

**Comment by aaronrussell** [comment]
@joeczucha since version 0.10.0 the routing has changed and the admin UI is mapped to the url `/admin` instead of `/push_type`.

The getting started guide is a little out of date - I'll get that fixed.
