### ISSUE TITLE
Incorrect file size next to assets is incorrect

### ISSUE THREAD

**Issue by jordelver** [pushtype/push_type#3]
Reports "58211 kb" but those are bytes, not kilobytes. We should either display bytes so as to be correct, or, perhaps more usefully, format to actual kilobytes.

<img width="802" alt="2015-08-24 at 23 03" src="https://cloud.githubusercontent.com/assets/6588/9473760/7e8c807a-4b54-11e5-9136-ef3166b5f8a2.png">

**Comment by aaronrussell** [comment]
https://discuss.pushtype.org/t/incorrect-file-size-next-to-assets-is-incorrect/22
