### ISSUE TITLE
Improve first time user experience after installation

### ISSUE THREAD

**Issue by jordelver** [pushtype/push_type#4]
The message says that "Better sort this one out now and create your first piece of content.". 

We cannot because there are no Nodes defined yet. It does says this in the documentation, but I think it would be a good idea to link directly from this page to the documentation about how to create nodes. "You need to create a Node before you can create any content" with a link to here: http://www.pushtype.org/docs/nodes/

<img width="790" alt="2015-08-24 at 22 10" src="https://cloud.githubusercontent.com/assets/6588/9473783/a7dd40b8-4b54-11e5-92b7-6d8470b4acc9.png">

**Comment by aaronrussell** [comment]
https://discuss.pushtype.org/t/improve-first-time-user-experience-after-installation/23
