### ISSUE TITLE
railties conflict for Rails 5.1 project

### ISSUE THREAD

**Issue by bennypaulino** [pushtype/push_type#41]
There is no longer a hard limit on railties < 5.1 for devise. As seen here:  

https://github.com/plataformatec/devise/blob/0fe308e7a77ff4f4e41228c04c109ce0178f4d4f/gemfiles/Gemfile.rails-5.1-stable.lock#L16  

and here:  

https://github.com/plataformatec/devise/blob/4beeca46c45dcb2fbc7513570dbc30dcbe3cc85a/devise.gemspec#L24

`bundle install` fails after adding `gem 'push_type', '~> 0.11.0.beta.1'` to the Gemfile, and running the command for `bundle update` yields the following:
```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    push_type (~> 0.11.0.beta.1) was resolved to 0.11.0.beta.1, which depends on
      push_type_auth (= 0.11.0.beta.1) was resolved to 0.11.0.beta.1, which depends on
        devise (~> 4.2.1) was resolved to 4.2.1, which depends on
          railties (< 5.1, >= 4.1.0)

    rails (~> 5.1.0) was resolved to 5.1.0, which depends on
      railties (= 5.1.0)
```

**Comment by aaronrussell** [comment]
Thanks. I'll look in to this.

**Comment by aaronrussell** [comment]
PushType is ready to go on this, but we need Devise to release a new version: See plataformatec/devise#4525 - As soon as they release a new gem I can release ours.

In the meantime you can use the latest beta 0.11.0.beta.2 and add this to your gem file:

    gem 'devise', git: 'https://github.com/plataformatec/devise.git', branch: 'master'

**Comment by bennypaulino** [comment]
Works a treat! I can have my cake and eat it too. Thanks, Aaron, for the provisional work-around!

**Comment by aaronrussell** [comment]
Cool, glad that worked. I'm going to keep this issue open just to remind me to release the gem once devise release their rails 5.1 version.

**Comment by NotTheUsual** [comment]
I'm still getting an error trying to set up a project like this.
Gemfile:
```ruby
gem 'push_type', '~> 0.11.0.beta.2'
gem 'devise', git: 'https://github.com/plataformatec/devise.git', branch: 'master'
```
Output
```
Bundler could not find compatible versions for gem "devise":
  In Gemfile:
    devise

    push_type (~> 0.11.0.beta.2) was resolved to 0.11.0.beta.2, which depends on
      push_type_auth (= 0.11.0.beta.2) was resolved to 0.11.0.beta.2, which depends on
        devise (~> 4.2.1)
```

**Comment by mysmallidea** [comment]
`auth/push_type_auth.gemspec` is [locked to devise 4.2.1](https://github.com/pushtype/push_type/blob/master/auth/push_type_auth.gemspec#L24), which requires Rails<5.1. 

Devise latest (4.3.0) has been updated updated to Rails<5.2. Is it possible to update the gemspec? 

Would you like a PR? I did update my gemspec locally, but I'm not able to run the test suite due to the webpack limitation.

**Comment by aaronrussell** [comment]
@mysmallidea thanks for offering to help, although I'm already on this so no need on this occasion. New release should be out tonight.

**Comment by aaronrussell** [comment]
The new release is out now - `v0.11.1` (skipped a version because I botched 0.11.0 previously and had to yank it). With the latest version there's no need to reference devise from github.
