### ISSUE TITLE
couldn't find file './webpack/admin.bundle' when running rake:test

### ISSUE THREAD

**Issue by mysmallidea** [pushtype/push_type#42]
I have pulled down the repo and I'm trying to run `rake test`. The test has initialized correctly and it runs until it gets to the admin module. Then I get: 

```
Error:
PushType::Admin::NodesControllerTest::GET #index#test_0001_anonymous:
ActionView::Template::Error: couldn't find file './webpack/admin.bundle' under '/Users/ryenski/Projects/push_type/admin/app/assets/javascripts' with type 'application/javascript'
Checked in these paths:
  /Users/ryenski/Projects/push_type/admin/test/dummy/app/assets/config
  /Users/ryenski/Projects/push_type/admin/test/dummy/app/assets/javascripts
# ... etc
```

**Comment by aaronrussell** [comment]
When working with the repo you'll need to install have a node environment setup. So when you first clone the repo do the following:

```
> cd admin
> npm install
> rake webpack
```

I think there is a good argument for committing the compiled javascript to the repo. I'm working on a new version of the admin UI now and this will be committed, but even then you'll still need a node environment when working with the code locally.

**Comment by mysmallidea** [comment]
I just found that on the contributing page - tests passed with (lots of) flying colors. Yay for actually reading the readme file!
Thanks!
