### ISSUE TITLE
Save / Publish button confusing

### ISSUE THREAD

**Issue by jordelver** [pushtype/push_type#5]
I found the button confusing. If you want to publish the page you have to select "Save and publish" and then press publish. I think it would better to just have two buttons?

<img width="386" alt="2015-08-24 at 22 58" src="https://cloud.githubusercontent.com/assets/6588/9473813/c8f8b016-4b54-11e5-97cc-c28305ad4cb9.png">

What do you think?

**Comment by aaronrussell** [comment]
https://discuss.pushtype.org/t/save-publish-button-confusing/24/3
